# Generated by Django 3.2.4 on 2021-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
