# Generated by Django 3.2.4 on 2021-09-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HyperionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
